name: Add user name

on:
  workflow_dispatch: {}
  pull_request:
    types: [opened]

jobs:
  add-user-name:
    runs-on: windows-latest
    
    env:
      RENAME_SCRIPT: ../scripts/update_cs_file_headers.py
      PR_BRANCH_NAME: ${{github.event.pull_request.head.ref}}
      TARGET_BRANCH_NAME: ${{github.event.pull_request.base.ref}}
      CREATED_BY_HEADER: "//Created By:"
      EDITED_BY_HEADER: "//Edited By:"
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Set Up Python (If Necessary)
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    
    - name: Set Up Python Libraries
      run: |
        python -m ensurepip --upgrade
        pip install GitPython
        pip install Github
    
    - name: Scan Text in .cs Files using Python script
      run: |
        # Get the list of modified .cs files in the pull request
        echo "PR branch: ${{env.PR_BRANCH_NAME}}"
        echo "Target branch: ${{env.TARGET_BRANCH_NAME}}"
        python ${{ env.RENAME_SCRIPT }} ${{github.workspace}} ${{env.PR_BRANCH_NAME}} ${{env.TARGET_BRANCH_NAME}} "${{env.CREATED_BY_HEADER}}" "${{env.EDITED_BY_HEADER}}"
        
    # - name: Read file
    #   id: read
    #   uses: actions/read-file@v2
    #   with:
    #     path: "**/*.cs"
    
    # - name: Add user name
    #   if: ${{ !contains(steps.read.output, 'Created by') }}
    #   uses: actions/edit-file@v2
    #   with:
    #     path: "*.cs"
    #     insert: |
    #       // Created by: ${{ github.actor }}

    # - name: Add user name
    #   if: ${{ contains(steps.read.output, 'Created by ') && !contains(steps.read.output, "Edited by) && !contains(steps.read.output, ${{ github.actor }}") }}
    #   uses: actions/edit-file@v2
    #   with:
    #     path: "*.cs"
    #     insert: |
    #       // Edited by ${{ github.actor }}
