name: Add user name

on:
  workflow_dispatch: {}
#   pull_request:
#     types: [opened]

jobs:
  add-user-name:
    runs-on: windows-latest
    
    env:
      RENAME_SCRIPT: ../scripts/update_cs_file_headers.py

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Set Up Python (If Necessary)
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    
    - name: Set Up Python Libraries
      run: |
        python -m ensurepip --upgrade
        pip install GitPython
        pip install Github
    
    - name: Scan Text in .cs Files using Python script
      run: |
        # Get the list of modified .cs files in the pull request
        $changedFileNames = git diff --name-only HEAD $(git merge-base HEAD ${{ github.base_ref }}) -- '*.cs'
        
        function Update-GHAFileHeader {
            param ( [string]$file )
            Write-Host "Preparing to run python script `"${{ env.RENAME_SCRIPT }}`" on $file"
            python ${{ env.RENAME_SCRIPT }} $file
        }
        
        if ($changedFileNames.GetType() -ne [System.Array]) {
            Update-GHAFileHeader -file $changedFileNames #if not an array, pass it directly
        } else {
            # Loop through each modified .cs file and scan its content
            foreach ($file in $changedFileNames) {
                Update-GHAFileHeader -file $file
            }
        }
    
    # - name: Read file
    #   id: read
    #   uses: actions/read-file@v2
    #   with:
    #     path: "**/*.cs"
    
    # - name: Add user name
    #   if: ${{ !contains(steps.read.output, 'Created by') }}
    #   uses: actions/edit-file@v2
    #   with:
    #     path: "*.cs"
    #     insert: |
    #       // Created by: ${{ github.actor }}

    # - name: Add user name
    #   if: ${{ contains(steps.read.output, 'Created by ') && !contains(steps.read.output, "Edited by) && !contains(steps.read.output, ${{ github.actor }}") }}
    #   uses: actions/edit-file@v2
    #   with:
    #     path: "*.cs"
    #     insert: |
    #       // Edited by ${{ github.actor }}
