name: Branch Cleanup

on:
  workflow_dispatch: {}
#  schedule:
#    - cron:  '0 0 * * 0'  # This means every Sunday at 00:00

jobs:
  branch-cleanup:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Run script
      run: |
        TOKEN="${{ secrets.GITHUB_TOKEN }}"
        OWNER="${{ github.repository_owner }}"
        REPO="${{ github.repository }}"
        branches_json=$(curl -H "Authorization: token $TOKEN" -s https://api.github.com/repos/$OWNER/$REPO/branches)
        branch_count=$(echo "$branches_json" | jq '. | length')
        for (( i=0; i<$branch_count; i++ ))
        do
          branch=$(echo "$branches_json" | jq -r ".[$i].name")
          last_commit_date=$(curl -H "Authorization: token $TOKEN" -s https://api.github.com/repos/$OWNER/$REPO/commits/$branch | jq -r '.commit.committer.date')
          echo "Branch: $branch, Last commit date: $last_commit_date"
          if [[ $last_commit_date != "null" ]]
          then
            last_commit_timestamp=$(date --utc -d "$last_commit_date" +%s)
            fifteen_minutes_ago=$(date --utc -d '15 minutes ago' +%s)
            if [[ $last_commit_timestamp -lt $fifteen_minutes_ago ]]
            then
              echo "Stale branch: $branch, Last commit more than 15 minutes ago"
            fi
          fi
        done
