name: Archive old branches

on:
  workflow_dispatch: {}
  schedule:
    # Run job every week
    - cron: '0 0 * * 1-5'

jobs:
  archive-old-branches:
    runs-on: ubuntu-latest
    steps:
    - name: Archive old branches
      run: |
        one_week_ago=$(date -d '1 week ago' -u +'%Y-%m-%dT%H:%M:%SZ')
        repo="${GITHUB_REPOSITORY}"
        branches=$(curl -H "Accept: application/vnd.github.v3+json" \
                 -H "Authorization: Bearer ${{ secrets.rking1189_PAT }}" \
                 https://api.github.com/repos/$repo/branches)
        branch_names=$(echo "$branches" | grep -o '"name":"[^"]*' | cut -d':' -f2 | tr -d '"')
        stale_branch_found=false
        for branch in $branch_names; do
          echo Branch name: $branch
          if [[ "$branch" == "main" || "$branch" == "master" || "$branch" == "dev" || "$branch" == "development" || "$branch" == "dev-iteration" ]]; then
            continue
          fi
          branch_info=$(curl -H "Accept: application/vnd.github.v3+json" \
                         -H "Authorization: Bearer ${{ secrets.rking1189_PAT }}" \
                         https://api.github.com/repos/$repo/branches/$branch)
          last_commit_date=$(echo "$branch_info" | grep -o '"commit":{"sha":"[^"]*' | cut -d':' -f4 | cut -d',' -f1 | tr -d '"')
          if [[ "$last_commit_date" < "$one_week_ago" ]]; then
            stale_branch_found=true
            new_branch_name="archive/$branch"
            echo $branch renamed to: $new_branch_name
            curl -X POST \
                 -H "Accept: application/vnd.github.v3+json" \
                 -H "Authorization: Bearer ${{ secrets.rking1189_PAT }}" \
                 https://api.github.com/repos/$repo/branches/$branch/rename \
                 -d '{"new_name":"'"$new_branch_name"'"}'
          fi
        done
        if ! $stale_branch_found; then
          echo "No stale branches to archive"
        fi
