name: Comment Checker

on:
  pull_request:
    types: [opened, reopened, edited]

jobs:
  is-comment-empty:
    runs-on: ubuntu-latest
    steps:
#        - name: basic exit
#          run: exit 1
#      - name: Lucky number
#        if: ${{ github.event.pull_request.body.indexOf('LuckyNumber') >= 0 }}
#        run: echo "Contains LuckyNumber"
    
      - name: Is comment empty?
        uses: actions/github-script@v6
        with: |
          if( github.event.pull_request.body == null ) {
              echo "Comment is empty."
              exit 1
#              core.setFailed('Comment is empty.')
          }
#        run: echo "Comment is empty."
#             exit 1
#          echo "Comment is empty."
#          (exit 1)
