# Created by: Ryan King

name: NightlyBuildCI

on:
  workflow_dispatch: {} # Can be run manually from actions page if needed.
  schedule:
    - cron: '0 4 * * 1-5' # Scheduled to run at 11PM Mon-Fri.

env:
  UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
  PROJECT_PATH: .

jobs:
  buildWithWindows:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%m-%d')"
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          lfs: true
          ref: dev-iteration
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.targetPlatform }}
      - uses: game-ci/unity-builder@v2
        with:
          buildName: Catmai_NightlyIteration_${{ steps.date.outputs.date }}
          targetPlatform: ${{ matrix.targetPlatform }}
      - name: Upload Build
        uses: actions/upload-artifact@v3
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build
