name: My Unity Build Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/Assembly-CSharp.csproj') }}

    - name: Build Unity Project
      uses: webbertakken/unity-builder@v2
      env:
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
      with:
        unityVersion: 2021.3.11f1
        targetPlatform: StandaloneWindows64
        projectPath: .
        buildName: build-StandaloneWindows64
        buildPath: build/StandaloneWindows64

    - uses: actions/upload-artifact@v2
      with:
        name: build-StandaloneWindows64
        path: build/StandaloneWindows64
